### ISSUE TITLE
Path to load 3rd party library incorrect in QRCode.js

### ISSUE THREAD

**Issue by gregorwolf** [jpenninkhof/openui5-qrcode#1]
I tried to use the control in my own project but had issues that the 3rd party library was not correctly loaded. I've fixed that by changing the line

`
    "com/penninkhof/qrcode/control/3rdparty/qrcode"
`

to

`
    "com/penninkhof/controls/3rdparty/qrcode"
`

in QRCode.js as this matches also the registerModulePath setting mentioned in the README.md

**Comment by jpenninkhof** [comment]
Thanks Gregor. Just fixed this!
