### ISSUE TITLE
QR Code needs white space to allow detection

### ISSUE THREAD

**Issue by gregorwolf** [jpenninkhof/openui5-qrcode#2]
For the [SAP Inside Track Munich 2016](http://sitmuc.de) we've tried to do the check in using the [SITregReceptionist](https://github.com/sapmentors/SITregReceptionist) to scan the QR-Code of the participants showing them in the [SITregParticipant](https://github.com/sapmentors/SITregParticipant) app. Unfortunately the scan from a smartphone failed. That's how the QR-Code is displayed i.e. on an iPhone 5:

![image](https://cloud.githubusercontent.com/assets/2639535/19223208/908224c4-8e6a-11e6-85e1-d99b28f8d44b.png)

According to [Quick Response Code - QR](http://ec.europa.eu/ipg/standards/qr_code/index_en.htm) there should be a white space around the QR Code of 4 [modules](http://www.qrcode.com/en/howto/cell.html).

**Comment by jpenninkhof** [comment]
Hey Gregor,

The QR code is actually generated by a 3rd party library, and I'd prefer not to change it (to be able to keep things in sync with the original version).

I'd advice to add class "sapUiMediumMargin" to the control and see if that works on the iPhone 5.

Cheers,
Jan

**Comment by gregorwolf** [comment]
Hi Jan,

I forgot to say that this was the [first thing I've tried](https://github.com/sapmentors/SITregParticipant/commit/3d9aef8315ae99f3d81b137d92ce8cbd1d06f66f) as soon as we've discovered the issue. Unfortunately the screenshot above was showing the old version. Here is the current one:

![image](https://cloud.githubusercontent.com/assets/2639535/19223798/b176fcbe-8e78-11e6-82ae-71d53e59b40f.png)

Unfortunately the top and bottom margin get removed in the mobile display.

Do you have a tip?

CU
Gregor
